"""create initial tables

Revision ID: f910a7d06eac
Revises: 
Create Date: 2026-10-10 14:08:04.884505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f910a7d06eac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('universitySubjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('studentSchedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pair_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['universitySubjects.subject_id'], ),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('student_id', 'date', 'pair_count', name='unique_student_schedule')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('marks',
    sa.Column('marks_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['studentSchedule.schedule_id'], ),
    sa.PrimaryKeyConstraint('marks_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_table('tokens')
    op.drop_table('studentSchedule')
    op.drop_table('user')
    op.drop_table('universitySubjects')
    op.drop_table('role')
    # ### end Alembic commands ###
